server:
  servlet:
    context-path:  /auth
  port: 7070
  
logging:
 level:
   org.springframework.security: DEBUG

public_key: | 
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyjMsAVNpTLl69Kn7qQ5L
  CiwbvBiASASHHvvoIMct/eXWcO+lVEnUjIDKSDtjr6Z1IBz/ZdN32ptvM93hxL48
  QFiK+cr1QFLS/UjnqjrniCQYZJmbyXXbWi/8/AnrYERn6NdINx34nnpIEWvhvLX9
  El+houbhNssBF61ktRzd0y4tL3msnW1EKK1cQ9SWWQzqvzcRntSRRiBaCWmixsHL
  EleGNLg5KfmEM0YkOhWH5tuwPAnTi+FGNebnh0O58PA8kFTMymYyPIgZg9jLLsys
  vwk0OVavoeLWQ47ZVIf/IIx3w9pj+CKbk7sGkBblY6iQpypAv8p83zUw0jPguC8y
  TwIDAQAB
  -----END PUBLIC KEY-----
  
private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAyjMsAVNpTLl69Kn7qQ5LCiwbvBiASASHHvvoIMct/eXWcO+l
  VEnUjIDKSDtjr6Z1IBz/ZdN32ptvM93hxL48QFiK+cr1QFLS/UjnqjrniCQYZJmb
  yXXbWi/8/AnrYERn6NdINx34nnpIEWvhvLX9El+houbhNssBF61ktRzd0y4tL3ms
  nW1EKK1cQ9SWWQzqvzcRntSRRiBaCWmixsHLEleGNLg5KfmEM0YkOhWH5tuwPAnT
  i+FGNebnh0O58PA8kFTMymYyPIgZg9jLLsysvwk0OVavoeLWQ47ZVIf/IIx3w9pj
  +CKbk7sGkBblY6iQpypAv8p83zUw0jPguC8yTwIDAQABAoIBACYwiA0wDeFZ3uk6
  +bcyZeXj8tER55iykjq95Vfbhso/kML/4EANOcHXyVzfKrLQQ6rvDyXSTP7TAKvR
  KoUYURTuJEGNnciqXANOs8KpIXXLK3hEsvHX+rgL/EI2NWiXQvDtSExwsrZr7hSs
  RZR44vWHbmXwKXVJ3kj0jOLQMu1ho0rMqG0EUokL5y+8FS8aSuA3G0pChqGG/xIN
  idfCFsDkTGXoAR+BGEA0P2jpn3eALfWUGuhIS2o9mUv4aBvbYPhip++dB/80h5bW
  SthPRKstRIvGA6pfebmd1YCaJ5Ww9TX3dNS12d7qf4RgPOsWbzst9fy8hzxD/3uE
  QDHd/6ECgYEA7iOxa6z1XPZRNrCaLh2E4Gqz8FKhZtc8P90ziI8VVD3X6+uJUWR3
  p448edCRCkxJkbLV1IYefTr2SiYtGb4teH3fB5tAhHW1izyfGDZM5n+ObbHb8z/T
  75/xpok01Oadg7upTd5t3T9n8dFT2Xt0o1Oe8eqzZyJ0G2vwY1mUCecCgYEA2V1v
  a6Imwbv3yylaJ84C2YKsq2IAmdMU5iglJTwZ3FD7QOUIijeK4l4MHTa+L2c0UUtS
  WNtBZ9jgaOXKD1ZNhifPusvasci23fU0Hx/Vax1Qge04+qs0/rCxsRGRShRdKzvC
  LHmIGZptqz/niz0Nnh9xTrGhfQwlpNvdvbAMF1kCgYEAnd8txLth4mItTvtfC0lo
  iLpUVfMBq0LvX0tO2a45rqJdHbsFSt827+68qukY7mHKt/t+BKlxVwYatud+KL3K
  OUIA9HL5H5dFZmwm8I83Bev0SUaLEUT0RLydIBF/49CLBgUH5WabIPzi9Q4X72sH
  1SsfiTNWAf52SKOTNtnw6WsCgYBq7ElY2uTRvBMCfw74MaC5OkyR6Z1+DZVkOi87
  h7r442UU4RU4WGYbQEQZQsp/KvdTXgfd6czctpR9RTwGG1/7NC49JvYnKiK6QFop
  TVGAZWUq5HR46ishde2Sup+Ln0TNdZHoqsfGQG7eJItTtO6z76efHEXh603BMN58
  5tKr0QKBgQCKBGoLpZO9EwK2L887MaWNFIHJZWRsQpOs8++Y9MI345khJSW1Lir6
  gK0ibkW9xW0Ut7K/nbeeryJDlouwTe+U+mfXAI/PAQfbbWYG9KXbH+NIIt8g2i6z
  i4tmSFuYP5Sfcbx7QXcJ6jJhAviFT2qQtXtL8TXVmj6h34o4Auf7EQ==
  -----END RSA PRIVATE KEY-----
    
   