server:
  servlet:
    context-path:  /auth
  port: 7070
  
logging:
 level:
   org.springframework.security: DEBUG

public_key: | 
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsfZE5kCZ9gKaRfFk6XEc
  blqRTxTlcgyTEKNaQmNCWTZJNmzDEQcMeSmDIVE3AqN1LUAWpbWLaRFhCB4CsPdC
  ztrjURr6aA7C82cgZmswS6gLnZvusMRvXt9sK3oco5JWSNy4H2jD03gj55Dy6CUF
  xEut6mwv35mvmreh6F7FbanBlFCmJ7iVXjlatfyvdttfe9uWsUre9r/qZTPSE2u1
  s86fjM2jgnA9D4U0F11kYy1lCn6qIHduY2S+OczOqPwWrh49EHjD8pnIiFxY7DmA
  Ob92zfEQpwvwbmqPB4sw9/pSRYs22s3Mid3vaGNbh/4cQjcEUR/c0sGm/702Gm5R
  HQIDAQAB
  -----END PUBLIC KEY-----
  
  
private_key: |
  -----BEGIN PRIVATE KEY-----
  MIICOAIBADANBgkqhkiG9w0BAQEFAASCAiIwggIeAgEAAoIBAQCx9kTmQJn2AppF
  8WTpcRxuWpFPFOVyDJMQo1pCY0JZNkk2bMMRBwx5KYMhUTcCo3UtQBaltYtpEWEI
  HgKw90LO2uNRGvpoDsLzZyBmazBLqAudm+6wxG9e32wrehyjklZI3LgfaMPTeCPn
  kPLoJQXES63qbC/fma+at6HoXsVtqcGUUKYnuJVeOVq1/K92219725axSt72v+pl
  M9ITa7Wzzp+MzaOCcD0PhTQXXWRjLWUKfqogd25jZL45zM6o/BauHj0QeMPymciI
  XFjsOYA5v3bN8RCnC/Buao8HizD3+lJFizbazcyJ3e9oY1uH/hxCNwRRH9zSwab/
  vTYablEdAgEAAoIBAH5MR8OdT2bfm/tNgQ+HfeT3k66rJtdVAz5IoDMDXMARnc3p
  TFsWRIzsoCqSB9dwiCWQGUKLYCA1/EYVflV3dct2XuNdoR8ecs7pfn4RTlozLeMy
  GikLj/ql14/XfuG7Zk8ZjfaElI3M8rZSEYIdXEVebFQ1aZhn6s+DyX0vXTAgmPXk
  5yNCUhHhoYaBNx5nblCLNqXmI9VgcBh8kAKftN9chBs7ENg3+8syS5UQLAMopFT2
  /yT0vMA16OXLCOprUk5sk7n+Y0m2iaHo/3WBOgrClo9alH09K3ukBIzR85DEdlvL
  yD5GyWdpawJOW8fwmbWyl9BJSKtlXwoMzi30PWUCAQACAQACAQACAQACAQA=
  -----END PRIVATE KEY-----  
  
    
   