package org.eso.oauth.server;
//package org.eso.oauth2.server;
//import static org.junit.Assert.*;
//
//import org.apache.tomcat.jni.Library;
///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//import org.junit.Test;
//
//public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//}
